### ISSUE TITLE
Please upgrade to Play 2.5

### ISSUE THREAD

**Issue by mkurz** [mumoshu/play2-memcached#46]
Should be very easy:
- sbt version is now 0.13.11
- Scala 2.10 was dropped, Scala version should be 2.11.7 only.

**Comment by dhirenpratap** [comment]
Unresolved dependency 
com.github.mumoshu:play2-memcached-play25_2.11:0.8.0

**Comment by dhirenpratap** [comment]
Any plan to upgrade it

**Comment by SoichiSumi** [comment]
won't be upgraded?

**Comment by adibsaad** [comment]
[2.5 is not on maven](https://mvnrepository.com/artifact/com.github.mumoshu), even though the readme says to use it, so it's probably a WIP.

**Comment by mumoshu** [comment]
I'm really open for someone to finish the PR https://github.com/mumoshu/play2-memcached/pull/47
The major difficulty for the PR seems to be coming from how we're supporting old Play versions via cross-building.
See https://github.com/mumoshu/play2-memcached/pull/47#issuecomment-206218775 for details

**Comment by djlitvak** [comment]
What have you guys been doing for using memcached with Play 2.5? I want to move my cache to aws elasticache soon.

**Comment by mkurz** [comment]
Fixed via #47 - new version should be released soon.
