### ISSUE TITLE
no retry/reconnect after timeout of memcache request - net.spy.memcached.internal.CheckedOperationTimeoutException

### ISSUE THREAD

**Issue by waheedma** [mumoshu/play2-memcached#48]
We have a setup of 2 app servers sharing the same memcache, we are seeing this error a lot 

ERROR memcached.plugin An error has occured while getting the value from memcached. ct=Any
1431624:net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node:
at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:160) ~[net.spy.spymemcached-2.9.0.jar:2.9.0]

The problem is once you hit this timeout, the memcached plugin never recovers/reconnects, and you always then see those errors all the time ? cant we retry or reconnect if we have a time out ? or is this more supposed to be solved in spy.memcached world ?

**Comment by waheedma** [comment]
UPDATE: Seems like it tries to reconnect, but only after X number of timeouts, we probably need to update the plugin to configure the number of timeouts it needs to wait before it tries to attempt to reconnect, according to this particular thread, the default threshold seems to be 99, http://stackoverflow.com/questions/22332203/spymemcached-and-connection-failures

**Comment by asog** [comment]
一样的问题，求解
