### ISSUE TITLE
Error accessing the cache after deploying to Heroku

### ISSUE THREAD

**Issue by clins777** [mumoshu/play2-memcached#53]
Hey guys!

Just informing that I am deploying with heroku and its the first time I have remote debugging configured (not sure if this can relate to the issue or not).

I am simply trying to set and read from the cache but the following errors occur.

```
[warn] memcached - Closing, and reopening {blablabla}, attempt 0.
[warn] memcached - Discarding partially completed op: Cmd: get Keys: play1406683782792716_1319587618164706Exp: 0
[error] m.plugin - An error has occured while getting the value from memcached. ct=Any. key=1406683782792716_1319587618164706. spymemcached code: CANCELLED memcached code:cancelled
[warn] memcached - Could not redistribute to another node, retrying primary node for play1406683782792716_1319587618164706.
```

(after this it retries twice and produces the same outcome)

I've tried a few things but no success including switching from memcachedcloud to memcachier.

What is strange is that the cache configuration is running ok on a different heroku app.

Please help me get to the bottom of this.

Thanks

**Comment by caionovaes** [comment]
Guys, I made a minimal app that you can run to reproduce the error: https://github.com/caionovaes/play2-memcached-test

It works fine locally but when deployed to heroku shows the log described on the last message.
